server:
  port: 8082
spring:
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件最大大小
      max-request-size: 500MB # 所有文件最大大小
      enabled: true
  jackson:
    # 格式化全局时间字段
    date-format: yyyy-MM-dd HH:mm:ss
    # 指定时间区域类型
    time-zone: Asia/Yekaterinburg
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.236.101:3306/jm_music?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Yekaterinburg
    username: root
    password: Jlf.123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1 # 验证连接有效性的 SQL 查询语句
      test-on-borrow: false # 在从连接池中借用（borrow）连接时，是否先验证连接的有效性。
      test-while-idle: true # 在连接空闲时是否验证连接的有效性
  data: # 配置redis地址 端口号
    redis:
      host: 192.168.236.101  # ip地址
      port: 6379  # 端口号
      database: 1
      timeout: 10s
      lettuce:
        pool:
          max-wait: -1 # 获取连接最大等待时间 -1 表示无限等待
          max-idle: 10 # 最大空闲连接数
          min-idle: 5 # 最小空闲连接数
          max-active: 50 # 最大活动连接数

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 将 SQL 日志输出到控制台
    map-underscore-to-camel-case: true # 开启自动驼峰映射
  mapper-locations: classpath*:mapper/*Mapper.xml # mybatis映射文件的位置
  type-aliases-package: com.jlf.music.entity
  global-config:
    # 将删除操作改为更新操作(逻辑删除)
    db-config:
      logic-delete-field: deleteFlag # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
minio:
  endpoint: http://192.168.236.101:9000 # MinIO服务器地址
  accessKey: minioadmin # MinIO 访问密钥(用户名)
  secretKey: minioadmin # MinIO 密钥(密码)